name: ShellCheck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ShellCheck
      uses: ludeeus/action-shellcheck@0.2.1
